
a = 3

a

b = "Ajay"

b

b[2]

b[-2]

#anaother type of data container
list_cont = [1, 2, 3, "Ajay", 3+5j, True, "a"]

type(list_cont)

list_cont[3]

list_cont[3] = "Bijay"

list_cont

#objects/container whose state or value can be changed after they are created are called mutable objects

b = "pwskills"

b[2]

b[2] = "I"

#objects/container whose state or value can not be changed after they are created are called immutable objects