

variable_name = "" # @param {"type":"string"}
#what is operator>>> special keywords to perform operations
#why? To manipualte data


#arithmatic operator
a = 5
b = 2
a+b

add = 5+2
print(add)

add

5+2

20 - 3

3 * 4

20 / 4

#modulus operator
17 % 4

2 ** 3 #2*2*2

3 ** 2

4/ 3

4 // 3 #floor operator

a = 2

# Comparison operator >> compare two values>> return a boolean value

2 == 2

2 != 2

5 != 2

10>2

10 < 5

10 >= 10

10 >= 1

10<=10

10 <= 12

10 >= 12

#Logical operator
#and
True and True

True and False

False and True

False and False

True or False

False or True

#Not operator
not True

not False

#Assignment operator

a  =10

a

a + 5

a

a = a + 10

a

a += 5

a

a

a *= 2

a

a

a /= 3

a

#membership operator

a = "PWSKILLS"

"P" in a

"am" in "I am Ajay"

"data" in "PWSKILLS"

"data" not in "PWSKILLS"

a = ["data", "science", "ajay"]

"data" in a

#identity operator >> compare the memory location of two object
a = 2

b = 3

a is b

b is a

a = "Pw Skills"
b=a

b is a

a is b

a = "pwskills"
b = "data"
a is b

a is not b

#bitwise operator>> operations at bit level
10 & 10

18 & 3

bin(10)

bin(18)

bin(3)

bin(2)

3 | 5

bin(3)

bin(5)

#negation
~3

~100

~6

#Bitwise xor >> return 1 when exactly one operand is 1

5 ^ 3

bin(5)

bin(3)

bin(6)

#shift >> left shift and right shift

#left shift put no of zeros on right side

35 << 3

bin(35)

bin(280)

5 << 1

bin(5)

bin(10)

#Right shift operator >> remove the no of elements in the binary
280 >> 3

bin(280)

bin(35)

10 >> 1

bin(10)

bin(5)

## order of precedence
#execution will start from left
2+3-1

#always parenthesis

(5+3) - 4

4 - (5+3)

(10+5) + (8/2)

